In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
%matplotlib inline

### Load custom functions

- city_merge_and_sum('city', 'column', 'zipcode_dictionary', 'zipcode_dataset')

In [23]:
def city_merge_and_sum(city, column, zipcode_dictionary, zipcode_dataset):
    
  merged = pd.merge(zipcode_dictionary, zipcode_dataset, on="Zipcode")
  
  cols=[i for i in merged.columns if i not in ["Zipcode","City","County"]]
  for col in cols:
    merged[col]=pd.to_numeric(merged[col])
    
  return merged[merged['City']==city][column].sum()

# Where...
# city: 'city_name'
# column: 'column_of_interest'
# zipcode_dictionary: dataframe; make sure column for zipcode = 'zipcode'
# zipcode_dataset: dataframe; make sure column for zipcode = 'zipcode'

# and returns:
# the sum of the 'column_of_interest' for a given city

- cities_merge_and_sum('column', 'zipcode_dictionary', 'zipcode_dataset')

In [24]:

def cities_merge_and_sum(column, zipcode_dictionary, zipcode_dataset):
    merged = pd.merge(zipcode_dictionary, zipcode_dataset, on="Zipcode")
    
    cols=[i for i in merged.columns if i not in ['Zipcode','City','County']]
    for col in cols:
        merged[col]=pd.to_numeric(merged[col])

    City = []
    Value = []
    
    for x in sorted(list(set(zipcode_dictionary['City']))):
        City.append(x)
        Value.append(merged[merged['City']==x][column].sum())
    return City, Value

# Where...
# column: 'column_of_interest'
# zipcode_dictionary: dataframe; make sure column for zipcode = 'zipcode'
# zipcode_dataset: dataframe; make sure column for zipcode = 'zipcode'

# and returns two lists:
# (1) the cities, and
# (2) sum of the 'column_of_interest' for a all cities zipcode dinctionary

In [25]:
def cities_merge_and_average(column, zipcode_dictionary, zipcode_dataset):
    merged = pd.merge(zipcode_dictionary, zipcode_dataset, on="Zipcode")
    
    cols=[i for i in merged.columns if i not in ['Zipcode','City','County']]
    for col in cols:
        merged[col]=pd.to_numeric(merged[col])

    City = []
    Value = []
    
    for x in sorted(list(set(zipcode_dictionary['City']))):
        City.append(x)
        Value.append(merged[merged['City']==x][column].mean())
    return City, Value

In [26]:
# Below is for loop for rolling up many columns in a dataframe

#newDF = pd.DataFrame() #creates a new dataframe that's empty
#
#counter = 0
#zipcode_dataset = census_sum
#
#
#for column in zipcode_dataset.columns:
#
#    if column != 'Zipcode':
#        #print(counter)
#        City, Value = cities_merge_and_sum(column, zipcode_dictionary, zipcode_dataset)
#        if counter == 0:
#            newDF['City'] = City
#            newDF[column] = Value
#            counter +=1
#        else:
#            newDF[column] = Value
#            counter += 1

### Load the massachusettes zipcode dicitonary

In [51]:
# import the massachusettes zipcode dictionary
massachusetts_zipcode_dictionary = pd.read_csv('~/Desktop/new_insights/data_files/final_zipcode_dictionary.csv', dtype = 'str', index_col=False)
massachusetts_zipcode_dictionary = pd.DataFrame(massachusetts_zipcode_dictionary)
unique_cities = massachusetts_zipcode_dictionary['City'].unique()
len(unique_cities)

303

# Making a dataset with opioid prescription information

In [52]:
# import the prescription data
prescription_data = pd.read_csv('~/Desktop/new_insights/data_files/medicare_D_opioid_by_zipcode.csv', dtype = {'Zipcode': str},  index_col=False)
prescription_data.dtypes
prescription_data.head()

,Zipcode,Prescribers_2017,Opioid_Prescribers_2017,Opioid_Claims_2017,Long-Acting_Opioid_Claims_2017,Overall_Claims_2017,Prescribers_2016,Opioid_Prescribers_2016,Opioid_Claims_2016,Long-Acting_Opioid_Claims_2016,...,Prescribers_2014,Opioid_Prescribers_2014,Opioid_Claims_2014,Long-Acting_Opioid_Claims_2014,Overall_Claims_2014,Prescribers_2013,Opioid_Prescribers_2013,Opioid_Claims_2013,Long-Acting_Opioid_Claims_2013,Overall_Claims_2013
0,35004,21,6,1497,90,23929,16.0,8.0,1587.0,101.0,...,16.0,9.0,1519.0,174.0,15707.0,18.0,9.0,1338.0,35.0,18631.0
1,35005,6,4,2031,167,39855,6.0,4.0,1992.0,199.0,...,6.0,5.0,2044.0,266.0,34440.0,6.0,5.0,2010.0,240.0,35800.0
2,35007,132,69,19705,2907,243536,127.0,64.0,18771.0,2825.0,...,120.0,69.0,17001.0,2534.0,240389.0,117.0,69.0,18840.0,3079.0,252203.0
3,35010,68,31,11073,563,269166,67.0,31.0,11668.0,615.0,...,63.0,38.0,12421.0,591.0,252938.0,66.0,39.0,13566.0,880.0,254425.0
4,35016,16,9,2615,192,67190,15.0,11.0,2636.0,137.0,...,16.0,12.0,3537.0,91.0,81273.0,18.0,12.0,3577.0,104.0,80569.0

In [53]:
prescription_data_2017 = pd.DataFrame()
prescription_data_2017['Zipcode'] = prescription_data['Zipcode']
prescription_data_2017['Prescribers'] = prescription_data['Prescribers_2017']
prescription_data_2017['Opioid_Prescribers'] = prescription_data['Opioid_Prescribers_2017'] 
prescription_data_2017['Opioid_Claims'] = prescription_data['Opioid_Claims_2017'] 
prescription_data_2017['Long-Acting_Opioid_Claims'] = prescription_data['Long-Acting_Opioid_Claims_2017']
prescription_data_2017['Overall_Claims'] = prescription_data['Overall_Claims_2017']
prescription_data_2017.head()

,Zipcode,Prescribers,Opioid_Prescribers,Opioid_Claims,Long-Acting_Opioid_Claims,Overall_Claims
0,35004,21,6,1497,90,23929
1,35005,6,4,2031,167,39855
2,35007,132,69,19705,2907,243536
3,35010,68,31,11073,563,269166
4,35016,16,9,2615,192,67190

### Use cities_merge_and_sum() to sum the prescription data

In [54]:
zipcode_dictionary = massachusetts_zipcode_dictionary
zipcode_dataset = prescription_data_2017

city, prescribers = cities_merge_and_sum('Prescribers', zipcode_dictionary, zipcode_dataset)
city, opioid_prescribers = cities_merge_and_sum('Opioid_Prescribers', zipcode_dictionary, zipcode_dataset)
city, opioid_claims = cities_merge_and_sum('Opioid_Claims', zipcode_dictionary, zipcode_dataset)
city, long_acting_opioid_claims = cities_merge_and_sum('Long-Acting_Opioid_Claims', zipcode_dictionary, zipcode_dataset)
city, overall_claims = cities_merge_and_sum('Overall_Claims', zipcode_dictionary, zipcode_dataset)

In [55]:
data = {'City':city,
        'Prescribers':prescribers, 
        'Opioid Prescribers':opioid_prescribers,
        'Opioid Claims':opioid_claims, 
        'Long Acting Opioid Claims':long_acting_opioid_claims, 
        'Overall Claims':overall_claims
       }
massachusetts_city_prescription_dataframe = pd.DataFrame(data)
massachusetts_city_prescription_dataframe

,City,Prescribers,Opioid Prescribers,Opioid Claims,Long Acting Opioid Claims,Overall Claims
0,Abington,23,13,1526,238,57473
1,Acton,56,20,1337,92,78818
2,Acushnet,0,0,0,0,0
3,Adams,8,5,2136,368,44447
4,Agawam,41,15,2952,582,98170
...,...,...,...,...,...,...
298,Woburn,109,41,2696,183,76461
299,Worcester,2536,869,69543,9488,2044764
300,Worthington,15,9,1311,296,14285
301,Wrentham,22,9,1158,242,50940
302,Yarmouth,46,18,2050,226,76500

### Write the city prescription data to a file...

In [56]:
massachusetts_city_prescription_dataframe.to_csv('~/Desktop/new_insights/data_files/massachusetts_city_prescriptions.csv', index = False)